import io
from xhtml2pdf import pisa

def generate_radar_pdf(report: dict) -> bytes:
    """
    Converts the Radar Report dictionary into a PDF byte stream.
    Uses xhtml2pdf for native UTF-8 (Chinese/Russian) support.
    """
    # 1. Build the HTML template
    html_content = f"""
    <html>
    <head>
        <style>
            @page {{ size: A4; margin: 2cm; }}
            body {{ font-family: sans-serif; font-size: 11px; color: #333; line-height: 1.5; }}
            h1 {{ color: #1a365d; text-align: center; font-size: 22px; border-bottom: 2px solid #1a365d; padding-bottom: 10px; }}
            h2 {{ color: #2c5282; margin-top: 20px; font-size: 16px; border-bottom: 1px solid #cbd5e0; padding-bottom: 5px; }}
            h3 {{ color: #2d3748; font-size: 14px; margin-top: 15px; }}
            .meta {{ text-align: center; color: #718096; margin-bottom: 20px; }}
            .summary {{ background: #f7fafc; padding: 15px; border-left: 4px solid #2c5282; margin-bottom: 20px; }}
            .alert-box {{ background: #fff5f5; border-left: 4px solid #e53e3e; padding: 10px; margin-bottom: 10px; }}
            .alert-title {{ color: #c53030; font-weight: bold; }}
            .post {{ background: #edf2f7; padding: 8px; margin: 5px 0; border-radius: 4px; font-size: 10px; }}
            .platform-tag {{ font-weight: bold; color: #2b6cb0; }}
        </style>
    </head>
    <body>
        <h1>TZ Tourism Radar Report</h1>
        <div class="meta">
            <p><b>Report Date:</b> {report.get('reportDate', 'N/A')}</p>
            <p><b>Total Posts Analyzed:</b> {report.get('raw_post_count', 0)}</p>
        </div>
        
        <h2>Executive Summary</h2>
        <div class="summary">{report.get('executiveSummary', 'No summary available.')}</div>
        
        <h2>Crisis Alerts</h2>
    """
    
    # Add Crisis Alerts
    alerts = report.get('crisisAlerts', [])
    if alerts:
        for alert in alerts:
            content = alert.get('content_translated') or alert.get('content_original', 'No content')
            platform = alert.get('platform', 'Unknown')
            html_content += f"""
            <div class="alert-box">
                <div class="alert-title">[{platform}] Crisis Signal Detected</div>
                <p>{content[:400]}...</p>
            </div>
            """
    else:
        html_content += "<p>No critical crisis alerts detected in this scan.</p>"

    # Add Market Insights
    html_content += "<h2>Market Insights</h2>"
    for region, title in [('chinaInsights', 'China Market Insights'), ('russiaInsights', 'Russia Market Insights')]:
        insights = report.get(region, [])
        if insights:
            html_content += f"<h3>{title}</h3>"
            for insight in insights:
                trend = insight.get('trend', 'N/A')
                sentiment = insight.get('sentiment', 'N/A')
                action = insight.get('action', 'N/A')
                
                html_content += f"""
                <p><b>Trend:</b> {trend} | <b>Sentiment:</b> {sentiment}</p>
                <p><b>Recommended Action:</b> {action}</p>
                """
                
                # Add top 3 posts for this insight
                posts = insight.get('posts', [])
                for post in posts[:3]:
                    p_content = post.get('content_translated') or post.get('content_original', '')
                    p_platform = post.get('platform', '')
                    html_content += f"""
                    <div class="post">
                        <span class="platform-tag">[{p_platform}]</span> {p_content[:250]}...
                    </div>
                    """
                    
    html_content += """
        <br><br>
        <p style="text-align: center; color: #a0aec0; font-size: 9px;">
            Generated by TZ Tourism Radar SaaS | Geopolitical Intelligence for Tanzanian Tourism
        </p>
    </body>
    </html>
    """

    # 2. Convert HTML to PDF
    buffer = io.BytesIO()
    # pisa.CreatePDF returns a status object. False means success.
    pisa_status = pisa.CreatePDF(io.StringIO(html_content), dest=buffer, encoding='utf-8')
    
    if pisa_status.err:
        raise Exception(f"PDF Generation failed with error: {pisa_status.err}")
        
    buffer.seek(0)
    return buffer.getvalue()